default_platform(:android)

platform :android do
  desc "Build the Android Debug APK"
  lane :build do
    gradle(
      task: "assemble",
      build_type: "Debug",
      project_dir: "android/"
    )
  end
end
